name: "Composite Action Example"
description: "Runs linter and formatter"

runs:
  using: "composite"
  steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 15

    - name: 计算哈希
      uses: actions/hash-files@v1
      id: get-hash
      with:
        patterns: |-
          package.json
          package-lock.json

    - name: 设置缓存
      id: npm-cache
      uses: actions/cache@v3
      with:
        key: deploy-web-${{ steps.get-hash.outputs.hash }}
        path: ${{ GITHUB_WORKSPACE }}/node_modules

    - name: 安装依赖
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm i --registry=http://registry.npmmirror.com

# 设置默认的 shell 环境
default-run:
  shell: bash
