name: "Composite Action Example"
description: "Runs linter and formatter1-20250401"

runs:
  using: "composite"
  steps:
    - name: 计算哈希
      uses: seepine/hash-files@v1
      id: get-hash
      with:
        patterns: |-
          package.json
          package-lock.json

    - name: 设置缓存
      uses: actions/cache@v3
      with:
        key: deploy-web-${{ steps.get-hash.outputs.hash }}
        path: node_modules
        restore-keys: |
          deploy-web-

    - name: 安装依赖
      run: |
        echo "npm install"
        if [ "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]; then
          npm i --registry=https://registry.npmmirror.com
        fi
      shell: bash

    - name: 执行编译
      run: npm run build:${{env.MODE}}
      shell: bash

    # - name: Debug Network
    #   run: |
    #     curl -v https://github.com
    #     git ls-remote https://github.com/mingchangge/deployWeb.git
    #   shell: bash

    # - name: 生成并复制 CA 证书
    #   run: |
    #     openssl req -x509 -newkey rsa:4096 -days 365 -nodes \
    #       -keyout /tmp/ca.key \
    #       -out /tmp/ca.crt \
    #       -subj "/CN=dockerCA"
    #     mkdir -p /home/runner/.docker
    #     cp /tmp/ca.crt /home/runner/.docker/ca.pem
    #   shell: bash

    # - name: 检查 CA 证书文件
    #   run: ls -l /home/runner/.docker/ca.pem
    #   shell: bash
    - name: 调试 Docker 环境
      run: |
        echo "DOCKER_HOST: $DOCKER_HOST"
        echo "DOCKER_TLS_VERIFY: $DOCKER_TLS_VERIFY"
        docker version
        docker info
        ls -la /home/runner/.docker
        cat /home/runner/.docker/config.json 2>/dev/null || echo "无 Docker 配置文件"
      shell: bash

    - name: 构建准备
      uses: docker/setup-buildx-action@v3
      env:
        DOCKER_HOST: "tcp://localhost:2375"
        DOCKER_TLS_VERIFY: "0"
      with:
        driver: docker-container
        install: false
        use: true
        cache-binary: true
        cleanup: true
        driver-opts: image=192.168.21.157:5000/moby/buildkit #指定用于运行 BuildKit 的容器镜像--暂时没有


    # - name: 构建和发布镜像
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     #file: docker/Dockerfile
    #     push: true
    #     tags: 192.168.21.157:5000/deploy-web:${{env.docker-tag}}

    # - name: 更新镜像
    #   uses: actions-hub/kubectl@master #要求base64编码的kubeconfig 文件
    #   env:
    #     KUBE_CONFIG: ${{ env.kube-config }}
    #   with:
    #     args: set image deployment/deploy-web deploy-web=192.168.21.157:5000/deploy-web:${{ env.docker-tag }} -n ${{env.namespace}}

    # - name: 滚动更新
    #   uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ env.kube-config }}
    #   with:
    #     args: rollout restart deployment/deploy-web -n ${{env.namespace}}
