name: "Composite Action Example"
description: "Runs linter and formatter"

runs:
  using: "composite"
  steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 15

    - name: 计算哈希
      uses: actions/hash-files@v1
      id: get-hash
      with:
        paths: |
          package.json
          package-lock.json

    - name: 设置缓存
      uses: actions/cache@v3
      with:
        key: deploy-web-${{ steps.get-hash.outputs.hash }}
        path: ${{ github.workspace }}/node_modules
        restore-keys: |
          deploy-web-

    - name: 运行命令 - Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: echo Running on Windows

    - name: 运行命令 - Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: echo Running on Ubuntu

    - name: 安装依赖
      run: npm i --registry=https://registry.npmmirror.com
