name: "Composite Action Example"
description: "Runs linter and formatter"

runs:
  using: "composite"
  steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 15

    - name: 计算哈希
      uses: seepine/hash-files@v1
      id: get-hash
      with:
        patterns: |-
          package.json
          package-lock.json

    - name: 设置缓存
      uses: actions/cache@v3
      with:
        key: deploy-web-${{ steps.get-hash.outputs.hash }}
        path: node_modules
        restore-keys: |
          deploy-web-

    - name: 安装依赖
      run: |
        echo "npm install"
        if [ "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]; then
          npm i --registry=https://registry.npmmirror.com
        fi
      shell: bash

    - name: 执行编译
      run: npm run build:${{env.MODE}}
      shell: bash

    - name: 构建准备
      uses: actions/setup-buildx-action@v2
      with:
        driver-opts: image=ghub.lxq.com/buildkit

    - name: 构建和发布镜像
      uses: actions/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ghub.lxq.com/deploy-web:${{env.docker-tag}}

    - name: 更新镜像
      uses: actions/kubectl@master
      env:
        KUBE_CONFIG: ${{ env.kube-config }}
      with:
        args: set image deployment/deploy-web deploy-web=ghub.lxq.com/deploy-web:${{ env.docker-tag }} -n ${{env.namespace}}

    - name: 滚动更新
      uses: actions/kubectl@master
      env:
        KUBE_CONFIG: ${{ env.kube-config }}
      with:
        args: rollout restart deployment/deploy-web -n ${{env.namespace}}
