name: Deploy
on: [push]
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Run composite action
        uses: ./.github/actions/composite-action
      - run: echo "🎉 success!"
    env:
      if: ${{ github.ref_name == 'master' }}
      MODE: dev
      namespace: deploy-web-dev
