name: Deploy
on: [push]
jobs:
  build-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run composite action
        uses: ./.github/actions/composite-action
      - run: echo "🎉 success!"
    env:
      if: ${{ github.ref_name == 'master' }}
      MODE: dev
      namespace: deploy-web-dev
      docker-tag: latest
      kube-config: ${{ secrets.KUBE_CONFIG_DEV }}
