name: Docker CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean Docker and Buildx configurations
        run: |
          rm -rf /home/runner/.docker
          docker builder prune --all --force

      - name: Reinitialize Docker and Buildx
        run: |
          mkdir -p /home/runner/.docker
          echo "DOCKER_TLS_VERIFY=0" >> $GITHUB_ENV
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV
          docker buildx create --name mybuilder --driver docker --use

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t myimage .
